/* Project Euler Problem 2
 * Even Fibonacci numbers
 * 2016 Kenneth Jensen <kenneth@jensen.cf>
 * ---
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

void main(void) {
	unsigned int a, b, temp;
	unsigned long long int sum = 0;
	for (a = 0, b = 1; b < 4000000; temp = b, b += a, a = temp) {
		if (b % 2 == 0) sum += b;
		printf("%d ", b);
	}
	printf("\n%d\n", sum);
}
