/* Project Euler Problem 12
 * Highly divisible triangular number
 * 2016, Kenneth Jensen <kenneth@jensen.cf>
 * ---
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The 
 * first ten terms would be:
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * Let us list the factors of the first seven triangle numbers:
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 * What is the value of the first triangle number to have over five hundred 
 * divisors?
 */

#include <stdio.h>
#include <math.h>

void main(void) {
	long n=1, c=0, t=0, i=0;
	while (n!=0) {
		t += n;
		c = 2;
		for (i = 2; i <= sqrt(t); ++i) {
			if (!(t % i)) c += 2;
			if (c >= 500) {
				printf("%d\n", t);
				return;
			}
		}
		++n;
	}
}
